openapi: 3.0.0
info:
  title: Calendário Econômico
  version: 1.0.0
  description: Obtenha os resultados das reuniões/eventos que movimentam as cotações das moedas no mundo inteiro.

servers:
  - url: http://localhost:3000

tags:
  - name: Calendário

paths:
  /calendar:
    get:
      tags: 
        - Calendário
      summary: Fetches filtered calendar events.
      parameters:
        - in: query
          name: asset
          schema:
            type: string
          description: Filter events by asset. Ex:USD
        - in: query
          name: eventDescription
          schema:
            type: string
          description: Filter events by event description.
      responses:
        '200':
          description: A list of filtered calendar events.
          content:
            application/json:
              schema:
                type: object
                properties:
                  utc:
                    type: object
                    properties:
                      currentClock:
                        type: string
                      gmt:
                        type: string
                  listEvents:
                    type: array
                    items:
                      type: object
                      properties:
                        dateEvent:
                          type: string
                        eventTitle:
                          type: string
                        eventTime:
                          type: string
                        eventImportanceLevel:
                          type: string
                        eventAsset:
                          type: string
                        current:
                          type: string
                        expected:
                          type: string
                        previous:
                          type: string
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                type: string